import { Inject, Injectable } from "@nestjs/common";
import type { AppConfig } from "@sgc/config";
import { APP_CONFIG } from "../config/config.module";
import { DatabaseService } from "../database/database.service";
import type { TenantContext } from "../../shared/request-context";

type RuleInput={type:"low_stock"|"overdue_receivables"|"cancelled_sales";channel:"email";recipient:string;isActive:boolean};
type RuleRow={id:string;type:RuleInput["type"];channel:string;recipient:string};
@Injectable()
export class AlertsService {constructor(@Inject(DatabaseService)private readonly database:DatabaseService,@Inject(APP_CONFIG)private readonly config:AppConfig){}
  async rules(context:TenantContext){const result=await this.database.tenantQuery(context.tenantId,`SELECT id,type,channel,recipient,is_active AS "isActive",created_at AS "createdAt" FROM alert_rules WHERE tenant_id=$1 ORDER BY created_at DESC`,[context.tenantId]);return{data:result.rows};}
  async createRule(context:TenantContext,input:RuleInput){const result=await this.database.tenantQuery(context.tenantId,`INSERT INTO alert_rules (tenant_id,type,channel,recipient,is_active) VALUES ($1,$2,$3,$4,$5) RETURNING *`,[context.tenantId,input.type,input.channel,input.recipient,input.isActive]);return result.rows[0];}
  async events(context:TenantContext){const result=await this.database.tenantQuery(context.tenantId,`SELECT id,type,channel,recipient,status,payload,sent_at AS "sentAt",failure_reason AS "failureReason",created_at AS "createdAt" FROM alert_events WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 100`,[context.tenantId]);return{data:result.rows};}
  async run(context:TenantContext){const rules=await this.database.tenantQuery<RuleRow>(context.tenantId,"SELECT id,type,channel,recipient FROM alert_rules WHERE tenant_id=$1 AND is_active=true",[context.tenantId]);const signals=await this.signals(context);let created=0,sent=0;for(const rule of rules.rows){const payload=signals[rule.type];if(!payload.count)continue;const fingerprint=`${rule.id}:${new Date().toISOString().slice(0,10)}`;const event=await this.database.tenantQuery<{id:string}>(context.tenantId,`INSERT INTO alert_events (tenant_id,rule_id,type,channel,recipient,status,payload,fingerprint) VALUES ($1,$2,$3,$4,$5,'pending',$6,$7) ON CONFLICT (tenant_id,fingerprint) WHERE fingerprint IS NOT NULL DO NOTHING RETURNING id`,[context.tenantId,rule.id,rule.type,rule.channel,rule.recipient,JSON.stringify(payload),fingerprint]);const id=event.rows[0]?.id;if(!id)continue;created++;if(await this.send(rule,payload)){await this.database.tenantQuery(context.tenantId,"UPDATE alert_events SET status='sent',sent_at=now() WHERE tenant_id=$1 AND id=$2",[context.tenantId,id]);sent++;}}
    return{created,sent,pending:created-sent,providerConfigured:Boolean(this.config.RESEND_API_KEY)};}
  private async signals(context:TenantContext){const [low,overdue,cancelled]=await Promise.all([this.database.tenantQuery<{count:string}>(context.tenantId,`SELECT count(*)::text count FROM stock_balances sb JOIN products p ON p.id=sb.product_id WHERE sb.tenant_id=$1 AND sb.quantity<=p.min_stock ${context.branchId?"AND sb.branch_id=$2":""}`,context.branchId?[context.tenantId,context.branchId]:[context.tenantId]),this.database.tenantQuery<{count:string;total:string}>(context.tenantId,`SELECT count(*)::text count,COALESCE(sum(amount),0)::text total FROM accounts_receivable WHERE tenant_id=$1 AND status='open' AND due_date<CURRENT_DATE ${context.branchId?"AND branch_id=$2":""}`,context.branchId?[context.tenantId,context.branchId]:[context.tenantId]),this.database.tenantQuery<{count:string;total:string}>(context.tenantId,`SELECT count(*)::text count,COALESCE(sum(total_amount),0)::text total FROM sales WHERE tenant_id=$1 AND status='cancelled' AND cancelled_at>=now()-interval '24 hours' ${context.branchId?"AND branch_id=$2":""}`,context.branchId?[context.tenantId,context.branchId]:[context.tenantId])]);return{low_stock:{count:Number(low.rows[0]?.count??0),title:"Estoque abaixo do mínimo",detail:"Revise os produtos que exigem reposição."},overdue_receivables:{count:Number(overdue.rows[0]?.count??0),total:Number(overdue.rows[0]?.total??0),title:"Contas a receber vencidas",detail:"Existem recebíveis vencidos aguardando baixa."},cancelled_sales:{count:Number(cancelled.rows[0]?.count??0),total:Number(cancelled.rows[0]?.total??0),title:"Vendas canceladas nas últimas 24h",detail:"Revise cancelamentos recentes e suas justificativas."}};}
  private async send(rule:RuleRow,payload:{title:string;detail:string;count:number;total?:number}){if(!this.config.RESEND_API_KEY)return false;const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${this.config.RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:`Orien Alertas <${this.config.ALERT_FROM_EMAIL}>`,reply_to:this.config.SUPPORT_EMAIL,to:[rule.recipient],subject:`Orien · ${payload.title}`,html:`<div style="font-family:Arial;color:#0b1d3d"><h1>${payload.title}</h1><p>${payload.detail}</p><p><strong>Ocorrências:</strong> ${payload.count}</p>${payload.total!==undefined?`<p><strong>Total:</strong> ${payload.total.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</p>`:""}<hr><small>Alerta operacional enviado pela Orien.</small></div>`})});return response.ok;}
}
