import { BadRequestException, ForbiddenException, Inject, Injectable } from "@nestjs/common";
import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes } from "node:crypto";
import type { AppConfig } from "@sgc/config";
import { APP_CONFIG } from "../config/config.module";
import { DatabaseService } from "../database/database.service";

@Injectable()
export class PlatformService {
  constructor(@Inject(DatabaseService) private readonly database: DatabaseService, @Inject(APP_CONFIG) private readonly config: AppConfig) {}
  async assertOwner(userId: string, sessionId?: string, requireMfa=true) { const row=await this.database.pool.query<{email:string;active:boolean;mfa_enabled:boolean}>(`SELECT u.email,COALESCE(pa.is_active,false) active,COALESCE(pa.mfa_enabled,false) mfa_enabled FROM users u LEFT JOIN platform_admins pa ON pa.user_id=u.id WHERE u.id=$1 AND u.deleted_at IS NULL`,[userId]); if(!row.rows[0]||(row.rows[0].email.toLowerCase()!==this.config.PLATFORM_OWNER_EMAIL.toLowerCase()&&!row.rows[0].active))throw new ForbiddenException("Acesso restrito ao backoffice Orien."); if(requireMfa&&row.rows[0].mfa_enabled&&sessionId){const session=await this.database.pool.query("SELECT mfa_verified_at FROM sessions WHERE id=$1",[sessionId]);if(!session.rows[0]?.mfa_verified_at)throw new ForbiddenException("Confirme o código do autenticador para acessar o backoffice.");} }
  async mfaSetup(userId:string){await this.assertOwner(userId,undefined,false);const secret=base32(randomBytes(20));const recovery=Array.from({length:8},()=>randomBytes(5).toString("hex").toUpperCase());await this.database.pool.query(`INSERT INTO platform_admins (user_id,role,is_active,mfa_required,mfa_enabled,mfa_secret_encrypted,recovery_code_hashes) VALUES ($1,'superadmin',true,true,false,$2,$3::jsonb) ON CONFLICT (user_id) DO UPDATE SET mfa_secret_encrypted=EXCLUDED.mfa_secret_encrypted,recovery_code_hashes=EXCLUDED.recovery_code_hashes,mfa_enabled=false,updated_at=now()`,[userId,this.encrypt(secret),JSON.stringify(recovery.map(code=>createHash("sha256").update(code).digest("hex")))]);return{secret,recoveryCodes:recovery,issuer:"Orien Admin"}}
  async mfaVerify(userId:string,sessionId:string,code:string){await this.assertOwner(userId,undefined,false);const row=await this.database.pool.query<{mfa_secret_encrypted:string|null}>("SELECT mfa_secret_encrypted FROM platform_admins WHERE user_id=$1",[userId]);if(!row.rows[0]?.mfa_secret_encrypted)throw new BadRequestException("Configure o autenticador primeiro.");const secret=this.decrypt(row.rows[0].mfa_secret_encrypted),value=code.replace(/\s/g,"");if(![-1,0,1].some(offset=>totp(secret,offset)===value))throw new ForbiddenException("Código MFA inválido.");await this.database.pool.query("UPDATE platform_admins SET mfa_enabled=true,updated_at=now() WHERE user_id=$1",[userId]);await this.database.pool.query("UPDATE sessions SET mfa_verified_at=now() WHERE id=$1 AND user_id=$2",[sessionId,userId]);return{ok:true}}
  async overview(){const [tenants,active,users,sessions,mrr,overdue,webhooks]=await Promise.all([q(this.database,"SELECT count(*)::int total FROM tenants WHERE deleted_at IS NULL"),q(this.database,"SELECT count(*)::int total FROM tenants WHERE status='active' AND deleted_at IS NULL"),q(this.database,"SELECT count(*)::int total FROM users WHERE deleted_at IS NULL"),q(this.database,"SELECT count(*)::int total FROM sessions WHERE revoked_at IS NULL AND expires_at>now()"),q(this.database,"SELECT COALESCE(sum(p.price_cents),0)::int total FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.status IN ('active','trial')"),q(this.database,"SELECT count(*)::int total FROM subscriptions WHERE status IN ('past_due','overdue')"),q(this.database,"SELECT count(*)::int total FROM webhook_events WHERE status<>'processed' OR created_at>now()-interval '24 hours'" )]);return{tenants:tenants.total,activeTenants:active.total,users:users.total,activeSessions:sessions.total,mrrCents:mrr.total,overdueSubscriptions:overdue.total,recentWebhookEvents:webhooks.total}}
  async tenants(){const result=await this.database.pool.query(`SELECT t.id,t.name,t.slug,t.status,t.plan_slug AS "planSlug",t.created_at AS "createdAt",count(DISTINCT m.id)::int AS "membersCount",count(DISTINCT s.id)::int AS "subscriptionsCount" FROM tenants t LEFT JOIN memberships m ON m.tenant_id=t.id AND m.status='active' AND m.deleted_at IS NULL LEFT JOIN subscriptions s ON s.tenant_id=t.id WHERE t.deleted_at IS NULL GROUP BY t.id ORDER BY t.created_at DESC`);return{data:result.rows}}
  async tenantDetail(id:string){const [tenant,members,branches,integrations,recentSales]=await Promise.all([this.database.pool.query(`SELECT id,name,slug,status,plan_slug AS "planSlug",created_at AS "createdAt" FROM tenants WHERE id=$1 AND deleted_at IS NULL`,[id]),qp(this.database,"SELECT count(*)::int total FROM memberships WHERE tenant_id=$1 AND status='active' AND deleted_at IS NULL",[id]),qp(this.database,"SELECT count(*)::int total FROM branches WHERE tenant_id=$1 AND deleted_at IS NULL",[id]),this.database.pool.query(`SELECT provider,status,updated_at AS "updatedAt" FROM tenant_integrations WHERE tenant_id=$1`,[id]),qp(this.database,"SELECT count(*)::int total FROM sales WHERE tenant_id=$1 AND status='sold' AND created_at>now()-interval '30 days'",[id])]);if(!tenant.rows[0])throw new BadRequestException("Tenant não encontrado.");return{tenant:tenant.rows[0],members:members.total,branches:branches.total,integrations:integrations.rows,salesLast30Days:recentSales.total}}
  async updateTenant(actor:string,id:string,status:string){if(!["trial","active","past_due","suspended","cancelled"].includes(status))throw new BadRequestException("Status inválido.");const updated=await this.database.pool.query("UPDATE tenants SET status=$2,updated_at=now() WHERE id=$1 AND deleted_at IS NULL RETURNING id,name,status",[id,status]);if(!updated.rows[0])throw new BadRequestException("Tenant não encontrado.");await this.audit(actor,"tenant.status.updated","tenant",id,{status});return updated.rows[0]}
  async billing(){const result=await this.database.pool.query(`SELECT t.name AS "tenantName",s.status,p.name AS "planName",p.price_cents AS "priceCents",s.current_period_ends_at AS "periodEndsAt" FROM subscriptions s JOIN tenants t ON t.id=s.tenant_id LEFT JOIN plans p ON p.id=s.plan_id ORDER BY s.updated_at DESC LIMIT 100`);return{data:result.rows}}
  async supportNotes(tenantId:string){const result=await this.database.pool.query(`SELECT n.id,n.body,n.created_at AS "createdAt",u.name AS "authorName" FROM platform_support_notes n LEFT JOIN users u ON u.id=n.author_user_id WHERE n.tenant_id=$1 ORDER BY n.created_at DESC`,[tenantId]);return{data:result.rows}}
  async addSupportNote(actor:string,tenantId:string,body:string){if(body.trim().length<3)throw new BadRequestException("Nota muito curta.");const result=await this.database.pool.query("INSERT INTO platform_support_notes (tenant_id,author_user_id,body) VALUES ($1,$2,$3) RETURNING id,body,created_at AS \"createdAt\"",[tenantId,actor,body.trim()]);await this.audit(actor,"support.note.created","tenant",tenantId,{});return result.rows[0]}
  async health(){const [failed,integrations,backups]=await Promise.all([q(this.database,"SELECT count(*)::int total FROM webhook_events WHERE status<>'processed'"),q(this.database,"SELECT count(*)::int total FROM tenant_integrations WHERE status='disabled'"),q(this.database,"SELECT count(*)::int total FROM sessions WHERE revoked_at IS NULL AND expires_at>now()")]);return{api:"operational",database:"operational",redis:"operational",failedWebhooks:failed.total,disabledIntegrations:integrations.total,activeSessions:backups.total}}
  async retryWebhook(actor:string,id:string){const result=await this.database.pool.query("UPDATE webhook_events SET status='pending',attempts=attempts+1,updated_at=now() WHERE id=$1 RETURNING id",[id]);if(!result.rows[0])throw new BadRequestException("Webhook não encontrado.");await this.audit(actor,"webhook.retry.requested","webhook_event",id,{});return{ok:true,message:"Webhook colocado na fila para reprocessamento."}}
  async staff(){const result=await this.database.pool.query(`SELECT pa.id,u.email,u.name,pa.role,pa.is_active AS "isActive",pa.mfa_required AS "mfaRequired",pa.created_at AS "createdAt" FROM platform_admins pa JOIN users u ON u.id=pa.user_id ORDER BY pa.created_at DESC`);return{data:result.rows}}
  async addStaff(actor:string,email:string,role:string){if(!["superadmin","support","finance","operations"].includes(role))throw new BadRequestException("Perfil interno inválido.");const user=await this.database.pool.query<{id:string}>("SELECT id FROM users WHERE lower(email)=lower($1) AND deleted_at IS NULL",[email]);if(!user.rows[0])throw new BadRequestException("Crie ou convide o usuário antes de torná-lo operador interno.");const result=await this.database.pool.query(`INSERT INTO platform_admins (user_id,role,is_active,mfa_required) VALUES ($1,$2,true,true) ON CONFLICT (user_id) DO UPDATE SET role=EXCLUDED.role,is_active=true,mfa_required=true,updated_at=now() RETURNING id`,[user.rows[0].id,role]);await this.audit(actor,"platform.staff.granted","platform_admin",result.rows[0].id,{email,role});return{ok:true}}
  async audit(actor:string,action:string,entityType:string,entityId:string,metadata:Record<string,unknown>){await this.database.pool.query("INSERT INTO platform_audit_logs (actor_user_id,action,entity_type,entity_id,metadata) VALUES ($1,$2,$3,$4,$5::jsonb)",[actor,action,entityType,entityId,JSON.stringify(metadata)])}
  private encrypt(value:string){const iv=randomBytes(12),key=createHash("sha256").update(this.config.INTEGRATIONS_ENCRYPTION_KEY).digest(),cipher=createCipheriv("aes-256-gcm",key,iv);return Buffer.concat([iv,cipher.getAuthTag(),Buffer.concat([cipher.update(value),cipher.final()])]).toString("base64")}
  private decrypt(value:string){const data=Buffer.from(value,"base64"),key=createHash("sha256").update(this.config.INTEGRATIONS_ENCRYPTION_KEY).digest(),decipher=createDecipheriv("aes-256-gcm",key,data.subarray(0,12));decipher.setAuthTag(data.subarray(12,28));return Buffer.concat([decipher.update(data.subarray(28)),decipher.final()]).toString()}
}
async function q(db:DatabaseService,sql:string){const r=await db.pool.query<{total:number}>(sql);return r.rows[0]??{total:0}}
async function qp(db:DatabaseService,sql:string,params:unknown[]){const r=await db.pool.query<{total:number}>(sql,params);return r.rows[0]??{total:0}}
function base32(input:Buffer){const chars="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let bits=0,value=0,out="";for(const byte of input){value=(value<<8)|byte;bits+=8;while(bits>=5){out+=chars[(value>>>(bits-5))&31];bits-=5}}return out}
function fromBase32(value:string){const chars="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let bits=0,current=0,out:number[]=[];for(const char of value.toUpperCase()){const index=chars.indexOf(char);if(index<0)continue;current=(current<<5)|index;bits+=5;if(bits>=8){out.push((current>>>(bits-8))&255);bits-=8}}return Buffer.from(out)}
function totp(secret:string,offset=0){const step=Math.floor(Date.now()/30000)+offset,buffer=Buffer.alloc(8);buffer.writeUInt32BE(0,4);buffer.writeUInt32BE(step,4);const digest=createHmac("sha1",fromBase32(secret)).update(buffer).digest(),start=digest[digest.length-1]&15;return String((digest.readUInt32BE(start)&0x7fffffff)%1000000).padStart(6,"0")}
