import { BadRequestException, ForbiddenException, Inject, Injectable } from "@nestjs/common";
import type { AppConfig } from "@sgc/config";
import { APP_CONFIG } from "../config/config.module";
import { DatabaseService } from "../database/database.service";

@Injectable()
export class PlatformService {
  constructor(@Inject(DatabaseService) private readonly database: DatabaseService, @Inject(APP_CONFIG) private readonly config: AppConfig) {}
  async assertOwner(userId: string) { const row=await this.database.pool.query<{email:string;active:boolean}>(`SELECT u.email,COALESCE(pa.is_active,false) active FROM users u LEFT JOIN platform_admins pa ON pa.user_id=u.id WHERE u.id=$1 AND u.deleted_at IS NULL`,[userId]); if(!row.rows[0]||(row.rows[0].email.toLowerCase()!==this.config.PLATFORM_OWNER_EMAIL.toLowerCase()&&!row.rows[0].active))throw new ForbiddenException("Acesso restrito ao backoffice Orien."); }
  async overview(){const [tenants,active,users,sessions,mrr,overdue,webhooks]=await Promise.all([q(this.database,"SELECT count(*)::int total FROM tenants WHERE deleted_at IS NULL"),q(this.database,"SELECT count(*)::int total FROM tenants WHERE status='active' AND deleted_at IS NULL"),q(this.database,"SELECT count(*)::int total FROM users WHERE deleted_at IS NULL"),q(this.database,"SELECT count(*)::int total FROM sessions WHERE revoked_at IS NULL AND expires_at>now()"),q(this.database,"SELECT COALESCE(sum(p.price_cents),0)::int total FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.status IN ('active','trial')"),q(this.database,"SELECT count(*)::int total FROM subscriptions WHERE status IN ('past_due','overdue')"),q(this.database,"SELECT count(*)::int total FROM webhook_events WHERE status<>'processed' OR created_at>now()-interval '24 hours'" )]);return{tenants:tenants.total,activeTenants:active.total,users:users.total,activeSessions:sessions.total,mrrCents:mrr.total,overdueSubscriptions:overdue.total,recentWebhookEvents:webhooks.total}}
  async tenants(){const result=await this.database.pool.query(`SELECT t.id,t.name,t.slug,t.status,t.plan_slug AS "planSlug",t.created_at AS "createdAt",count(DISTINCT m.id)::int AS "membersCount",count(DISTINCT s.id)::int AS "subscriptionsCount" FROM tenants t LEFT JOIN memberships m ON m.tenant_id=t.id AND m.status='active' AND m.deleted_at IS NULL LEFT JOIN subscriptions s ON s.tenant_id=t.id WHERE t.deleted_at IS NULL GROUP BY t.id ORDER BY t.created_at DESC`);return{data:result.rows}}
  async tenantDetail(id:string){const [tenant,members,branches,integrations,recentSales]=await Promise.all([this.database.pool.query(`SELECT id,name,slug,status,plan_slug AS "planSlug",created_at AS "createdAt" FROM tenants WHERE id=$1 AND deleted_at IS NULL`,[id]),qp(this.database,"SELECT count(*)::int total FROM memberships WHERE tenant_id=$1 AND status='active' AND deleted_at IS NULL",[id]),qp(this.database,"SELECT count(*)::int total FROM branches WHERE tenant_id=$1 AND deleted_at IS NULL",[id]),this.database.pool.query(`SELECT provider,status,updated_at AS "updatedAt" FROM tenant_integrations WHERE tenant_id=$1`,[id]),qp(this.database,"SELECT count(*)::int total FROM sales WHERE tenant_id=$1 AND status='sold' AND created_at>now()-interval '30 days'",[id])]);if(!tenant.rows[0])throw new BadRequestException("Tenant não encontrado.");return{tenant:tenant.rows[0],members:members.total,branches:branches.total,integrations:integrations.rows,salesLast30Days:recentSales.total}}
  async updateTenant(actor:string,id:string,status:string){if(!["trial","active","past_due","suspended","cancelled"].includes(status))throw new BadRequestException("Status inválido.");const updated=await this.database.pool.query("UPDATE tenants SET status=$2,updated_at=now() WHERE id=$1 AND deleted_at IS NULL RETURNING id,name,status",[id,status]);if(!updated.rows[0])throw new BadRequestException("Tenant não encontrado.");await this.audit(actor,"tenant.status.updated","tenant",id,{status});return updated.rows[0]}
  async billing(){const result=await this.database.pool.query(`SELECT t.name AS "tenantName",s.status,p.name AS "planName",p.price_cents AS "priceCents",s.current_period_ends_at AS "periodEndsAt" FROM subscriptions s JOIN tenants t ON t.id=s.tenant_id LEFT JOIN plans p ON p.id=s.plan_id ORDER BY s.updated_at DESC LIMIT 100`);return{data:result.rows}}
  async supportNotes(tenantId:string){const result=await this.database.pool.query(`SELECT n.id,n.body,n.created_at AS "createdAt",u.name AS "authorName" FROM platform_support_notes n LEFT JOIN users u ON u.id=n.author_user_id WHERE n.tenant_id=$1 ORDER BY n.created_at DESC`,[tenantId]);return{data:result.rows}}
  async addSupportNote(actor:string,tenantId:string,body:string){if(body.trim().length<3)throw new BadRequestException("Nota muito curta.");const result=await this.database.pool.query("INSERT INTO platform_support_notes (tenant_id,author_user_id,body) VALUES ($1,$2,$3) RETURNING id,body,created_at AS \"createdAt\"",[tenantId,actor,body.trim()]);await this.audit(actor,"support.note.created","tenant",tenantId,{});return result.rows[0]}
  async health(){const [failed,integrations,backups]=await Promise.all([q(this.database,"SELECT count(*)::int total FROM webhook_events WHERE status<>'processed'"),q(this.database,"SELECT count(*)::int total FROM tenant_integrations WHERE status='disabled'"),q(this.database,"SELECT count(*)::int total FROM sessions WHERE revoked_at IS NULL AND expires_at>now()")]);return{api:"operational",database:"operational",redis:"operational",failedWebhooks:failed.total,disabledIntegrations:integrations.total,activeSessions:backups.total}}
  async retryWebhook(actor:string,id:string){const result=await this.database.pool.query("UPDATE webhook_events SET status='pending',attempts=attempts+1,updated_at=now() WHERE id=$1 RETURNING id",[id]);if(!result.rows[0])throw new BadRequestException("Webhook não encontrado.");await this.audit(actor,"webhook.retry.requested","webhook_event",id,{});return{ok:true,message:"Webhook colocado na fila para reprocessamento."}}
  async staff(){const result=await this.database.pool.query(`SELECT pa.id,u.email,u.name,pa.role,pa.is_active AS "isActive",pa.mfa_required AS "mfaRequired",pa.created_at AS "createdAt" FROM platform_admins pa JOIN users u ON u.id=pa.user_id ORDER BY pa.created_at DESC`);return{data:result.rows}}
  async addStaff(actor:string,email:string,role:string){if(!["superadmin","support","finance","operations"].includes(role))throw new BadRequestException("Perfil interno inválido.");const user=await this.database.pool.query<{id:string}>("SELECT id FROM users WHERE lower(email)=lower($1) AND deleted_at IS NULL",[email]);if(!user.rows[0])throw new BadRequestException("Crie ou convide o usuário antes de torná-lo operador interno.");const result=await this.database.pool.query(`INSERT INTO platform_admins (user_id,role,is_active,mfa_required) VALUES ($1,$2,true,true) ON CONFLICT (user_id) DO UPDATE SET role=EXCLUDED.role,is_active=true,mfa_required=true,updated_at=now() RETURNING id`,[user.rows[0].id,role]);await this.audit(actor,"platform.staff.granted","platform_admin",result.rows[0].id,{email,role});return{ok:true}}
  async audit(actor:string,action:string,entityType:string,entityId:string,metadata:Record<string,unknown>){await this.database.pool.query("INSERT INTO platform_audit_logs (actor_user_id,action,entity_type,entity_id,metadata) VALUES ($1,$2,$3,$4,$5::jsonb)",[actor,action,entityType,entityId,JSON.stringify(metadata)])}
}
async function q(db:DatabaseService,sql:string){const r=await db.pool.query<{total:number}>(sql);return r.rows[0]??{total:0}}
async function qp(db:DatabaseService,sql:string,params:unknown[]){const r=await db.pool.query<{total:number}>(sql,params);return r.rows[0]??{total:0}}
