services:
  migrate:
    image: ${ORIEN_API_IMAGE}
  api:
    image: ${ORIEN_API_IMAGE}
  worker:
    image: ${ORIEN_API_IMAGE}
  web:
    image: ${ORIEN_WEB_IMAGE}
  marketing:
    image: ${ORIEN_MARKETING_IMAGE}
  admin:
    image: ${ORIEN_ADMIN_IMAGE}
