server {
    listen 80;
    server_name useorien.com.br;

    location / {
        proxy_pass http://127.0.0.1:3101;
        include proxy_params;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name app.useorien.com.br;

    location / {
        proxy_pass http://127.0.0.1:3100;
        include proxy_params;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name api.useorien.com.br;

    location / {
        proxy_pass http://127.0.0.1:3334;
        include proxy_params;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
